#!/usr/bin/env python2
# -*- coding: utf-8 ; mode: python -*-

# Set the procname, if possible.
try:
    import procname
except ImportError:
    pass
else:
    import os
    import sys
    procname.setprocname(os.path.basename(sys.argv[0]))

import aqt
aqt.run()
